"use client";

import { useState, useEffect, useCallback } from "react";
import { useSession } from "next-auth/react";
import { useSearchParams } from "next/navigation";
import { useForm, FormProvider } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { z } from "zod";
import { toast } from "sonner";

import { DUNGEON_DEFAULT } from "@/types";
import { EditorInfoForm, EditorActionBar, TilePalette } from "@/app/(pages)/dungeons/_components";
import { useGetUser } from "@/app/_hooks";
import { useTileImages, useDungeonEditorLogic } from "@/app/(pages)/dungeons/_hook";
import { DungeonCanvasView } from "./DungeonCanvasView";
import { DungeonMetadataCard } from "./DungeonMetadataCard";
import { DungeonResponse } from "@/types";

// Zodによるバリデーションスキーマ
const dungeonSchema = z.object({
  code: z.string(),
  name: z.string().min(1, "ダンジョン名は必須入力です").max(50, "ダンジョン名は50文字以内で入力してください"),
  description: z.string().max(1000, "説明文は1000文字以内で入力してください"),
  timeLimit: z
    .number()
    .min(10, "制限時間は10秒以上に設定してください")
    .max(3600, "制限時間は1時間以内に設定してください"),
  mapDataCheck: z.any(), // 変更検知用の隠しフィールド（バリデーションは通すだけ）
});
export type DungeonFormData = z.infer<typeof dungeonSchema>; // 子側で使うためexport

interface DungeonEditorProps {
  initialData?: DungeonResponse; // 編集時は既存データが入る
  isAdmin: boolean;
}

export function DungeonEditor({ initialData, isAdmin }: DungeonEditorProps) {
  const { data: session } = useSession();
  const user = session?.user;

  if (!user) return toast.error("セッションが切断されました。再ログインしてください。");

  const { user: userInfo } = useGetUser(user.id);
  const searchParams = useSearchParams();

  // 管理者ダッシュボードのユーザーダンジョン「詳細ボタン」から遷移してきた場合
  // パレットパネルは閉じて、メタ情報パネルは開く
  const fromSource = searchParams.get("from");
  const isFromUserDetail = fromSource === "user-detail";
  const initialPaletteOpen = isFromUserDetail ? false : true;
  const initialMetadataOpen = isFromUserDetail ? true : false;

  const isEditMode = !!initialData?.id;

  // React Hook Form の初期化
  const methods = useForm<DungeonFormData>({
    resolver: zodResolver(dungeonSchema),
    defaultValues: {
      code: initialData?.code || "-",
      name: initialData?.name || "",
      description: initialData?.description || "",
      timeLimit: initialData?.timeLimit || DUNGEON_DEFAULT.TIME_LIMIT,
      mapDataCheck: JSON.stringify(initialData?.mapData?.tiles || []),
    },
  });

  const {
    handleSubmit,
    watch,
    setValue,
    formState: { errors, isDirty },
  } = methods;
  const formValues = watch();

  // ダンジョン名に初期値をセット
  useEffect(() => {
    // 新規作成モードかつ、APIからユーザー情報が取得できたタイミング
    if (!isEditMode && userInfo) {
      const nickName = userInfo.nickName || userInfo.userName || "Player";
      const nextNumber = (userInfo.activeDungeonCount || 0) + 1;
      const paddedNumber = String(nextNumber).padStart(3, "0");
      const autoGeneratedName = `${nickName}_${paddedNumber}`;
      // ユーザーがすでに自分で名前をタイピングし始めていない場合のみ、初期名をセット
      if (!formValues.name) {
        setValue("name", autoGeneratedName, { shouldValidate: true });
      }
    }
  }, [userInfo, isEditMode, setValue, formValues.name]);

  // ダンジョン編集ロジック取得
  const {
    tiles,
    entities,
    rows,
    cols,
    linkingState,
    handleCellClick,
    updateTilesSize,
    getEntityType,
    setRows,
    setCols,
  } = useDungeonEditorLogic(initialData);

  // キャンバスに対する操作を統合
  const [selectedTile, setSelectedTile] = useState("W");
  const handleCanvasAction = useCallback(
    (r: number, c: number) => {
      // ロジック側のタイル更新
      handleCellClick(r, c, selectedTile);
      // フォームのDirtyフラグを立てる
      setValue("mapDataCheck", `tile-${r}-${c}-${Date.now()}`, {
        shouldDirty: true,
        shouldValidate: true,
      });
    },
    [handleCellClick, selectedTile, setValue],
  );
  const { images, isLoaded } = useTileImages();

  return (
    <div className="min-h-screen bg-gray-950 text-white p-6">
      <div className="max-w-7xl mx-auto">
        {/* FormProviderで囲み、子コンポーネントがContext経由でReact Hook Formを扱えるようにする */}
        <FormProvider {...methods}>
          {/* onSubmitのデフォルト挙動を無効化 */}
          <form onSubmit={(e) => e.preventDefault()}>
            <header className="select-none flex flex-col lg:grid lg:grid-cols-[1fr_auto] lg:items-stretch gap-4 w-full mb-6">
              <div className="min-w-0 w-full bg-slate-900 border border-slate-800 rounded-xl shadow-2xl p-4 flex flex-col justify-center">
                <EditorInfoForm
                  status={initialData?.status ?? "DRAFT"}
                  config={formValues}
                  cols={cols}
                  rows={rows}
                  errors={errors}
                  onConfigChange={(k, v, b) => setValue(k as any, v, { shouldDirty: b, shouldValidate: true })}
                  onSizeChange={(r, c) => {
                    setRows(r);
                    setCols(c);
                    updateTilesSize(r, c);
                    setValue("mapDataCheck", `size-${r}-${c}-${Date.now()}`, { shouldDirty: true });
                  }}
                />
              </div>

              <div className="min-w-0 shrink-0 bg-slate-900 border border-slate-800 rounded-xl shadow-2xl p-4">
                <EditorActionBar
                  initialData={initialData}
                  isAdmin={isAdmin}
                  user={user}
                  tiles={tiles}
                  entities={entities}
                  rows={rows}
                  cols={cols}
                  linkingState={linkingState}
                />
              </div>
            </header>

            <div className="flex gap-6 mt-6 items-start">
              {/* 左サイドバー */}
              <aside className="w-64 flex-shrink-0 space-y-4">
                <TilePalette
                  selectedTile={selectedTile}
                  onSelect={(id) => {
                    if (linkingState.active && getEntityType(id) !== linkingState.pendingType && id !== "..") {
                      return toast.error("セット設置を優先してください");
                    }
                    setSelectedTile(id);
                  }}
                  defaultOpen={initialPaletteOpen}
                />

                <DungeonMetadataCard
                  initialData={initialData}
                  isEditMode={isEditMode}
                  isAdmin={isAdmin}
                  defaultOpen={initialMetadataOpen}
                />

                {linkingState.active && (
                  <div className="bg-amber-900/40 border border-amber-500 p-4 rounded-xl animate-pulse">
                    <p className="text-sm font-bold text-amber-400">Linking Mode</p>
                    <p className="text-xs">
                      {linkingState.pendingType === "DOOR" ? "扉" : "スイッチ"}を配置してください
                    </p>
                  </div>
                )}
              </aside>

              <main className="flex-1 bg-gray-900 border border-gray-800 rounded-xl overflow-auto p-12 h-[calc(100vh-160px)] min-h-[600px] flex">
                <DungeonCanvasView
                  tiles={tiles}
                  entities={entities}
                  rows={rows}
                  cols={cols}
                  images={images}
                  isLoaded={isLoaded}
                  linkingState={linkingState}
                  onCanvasAction={handleCanvasAction}
                />
              </main>
            </div>
          </form>
        </FormProvider>
      </div>
    </div>
  );
}
