"use client";

import { useState, useEffect, useCallback } from "react";
import { useSession } from "next-auth/react";
import { useSearchParams } from "next/navigation";
import { useForm, FormProvider } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { z } from "zod";
import { toast } from "sonner";

import { DUNGEON_DEFAULT, TILE_CATEGORIES } from "@/game-core/types";
import { TILE_CONFIG, TileConfigKey } from "@/game-core/master";
import { EditorInfoHeader, TilePalette } from "@/app/(pages)/dungeons/_components";
import { useGetUser } from "@/app/_hooks";
import { useTileImages, useDungeonEditorLogic, useEditorHistory } from "@/app/(pages)/dungeons/_hook";
import { DungeonCanvasView } from "./DungeonCanvasView";
import { DungeonMetadataCard } from "./DungeonMetadataCard";
import { DungeonResponse } from "@/app/_types";

// Zodによるバリデーションスキーマ
const dungeonSchema = z.object({
  code: z.string(),
  name: z.string().min(1, "ダンジョン名は必須入力です").max(50, "ダンジョン名は50文字以内で入力してください"),
  description: z.string().max(1000, "説明文は1000文字以内で入力してください"),
  timeLimit: z
    .number()
    .min(10, "制限時間は10秒以上に設定してください")
    .max(3600, "制限時間は1時間以内に設定してください"),
  mapDataCheck: z.any(), // 変更検知用の隠しフィールド（バリデーションは通すだけ）
});
export type DungeonFormData = z.infer<typeof dungeonSchema>; // 子側で使うためexport

interface DungeonEditorProps {
  initialData?: DungeonResponse; // 編集時は既存データが入る
  isAdmin: boolean;
}

export function DungeonEditor({ initialData, isAdmin }: DungeonEditorProps) {
  const { data: session } = useSession();
  const user = session?.user;

  if (!user) return toast.error("セッションが切断されました。再ログインしてください。");

  const { user: userInfo } = useGetUser(user.id);
  const searchParams = useSearchParams();

  // 管理者ダッシュボードのユーザーダンジョン「詳細ボタン」から遷移してきた場合
  // パレットパネルは閉じて、メタ情報パネルは開く
  const fromSource = searchParams.get("from");
  const isFromUserDetail = fromSource === "user-detail";
  const initialPaletteOpen = isFromUserDetail ? false : true;
  const initialMetadataOpen = isFromUserDetail ? true : false;

  const isEditMode = !!initialData?.id;

  // React Hook Form の初期化
  const methods = useForm<DungeonFormData>({
    resolver: zodResolver(dungeonSchema),
    defaultValues: {
      code: initialData?.code || "-",
      name: initialData?.name || "",
      description: initialData?.description || "",
      timeLimit: initialData?.timeLimit || DUNGEON_DEFAULT.TIME_LIMIT,
      mapDataCheck: 0,
    },
  });

  const { watch, setValue } = methods;
  const formValues = watch();

  const {
    tiles,
    entities,
    rows,
    cols,
    linkingState,
    handleCellClick,
    updateTilesSize,
    getEntityType,
    setRows,
    setCols,
    setTilesState,
    setEntitiesState,
  } = useDungeonEditorLogic(initialData);

  const { canUndo, canRedo, handleUndo, handleRedo, pushHistory, getCurrentSnapshot, setHistory } = useEditorHistory(
    methods,
    tiles,
    entities,
    rows,
    cols,
    setRows,
    setCols,
    setTilesState,
    setEntitiesState,
  );

  // 初期名生成ロジック
  useEffect(() => {
    if (!isEditMode && userInfo && !formValues.name) {
      const nickName = userInfo.nickName || userInfo.userName || "Player";
      const nextNumber = (userInfo.activeDungeonCount || 0) + 1;
      const autoGeneratedName = `${nickName}_${String(nextNumber).padStart(3, "0")}`;

      setValue("name", autoGeneratedName, { shouldValidate: true });

      const snap = getCurrentSnapshot();
      snap.name = autoGeneratedName;
      setHistory([snap]);
    }
  }, [userInfo, isEditMode, setValue, getCurrentSnapshot, setHistory]);

  // 編集履歴キーボードショートカット
  useEffect(() => {
    const handleKeyDown = (e: KeyboardEvent) => {
      if ((e.ctrlKey || e.metaKey) && !e.shiftKey && e.key.toLowerCase() === "z") {
        e.preventDefault();
        handleUndo();
      }
      if ((e.ctrlKey || e.metaKey) && e.key.toLowerCase() === "y") {
        e.preventDefault();
        handleRedo();
      }
    };
    window.addEventListener("keydown", handleKeyDown);
    return () => window.removeEventListener("keydown", handleKeyDown);
  }, [handleUndo, handleRedo]);

  // タイル配置アクション
  const [selectedTile, setSelectedTile] = useState<TileConfigKey>("W");
  const handleCanvasAction = useCallback(
    (r: number, c: number) => {
      if (r <= 0 || r >= rows - 1 || c <= 0 || c >= cols - 1) return;
      if (selectedTile !== " " && TILE_CONFIG[selectedTile]?.category === TILE_CATEGORIES.PLAYER) {
        const hasPlayer = tiles.flat().some((t) => TILE_CONFIG[t]?.category === TILE_CATEGORIES.PLAYER);
        if (hasPlayer) return toast.error("プレイヤーは1つのみです");
      }

      handleCellClick(r, c, selectedTile);

      const nextSnapshot = {
        ...getCurrentSnapshot(),
        tiles: tiles.map((row, ri) =>
          row.map((cell, ci) => (ri === r && ci === c ? (selectedTile === " " ? " " : selectedTile) : cell)),
        ),
      };
      pushHistory(nextSnapshot);
    },
    [handleCellClick, selectedTile, tiles, rows, cols, getCurrentSnapshot, pushHistory],
  );

  const { images, isLoaded } = useTileImages();

  const getLinkingGuideMessage = () => {
    if (!linkingState.active) return null;

    if (linkingState.mode === "KEY_DOOR") {
      return linkingState.pendingType === "KEY_DOOR"
        ? "「鍵扉」を配置して、鍵とペアリングさせてください"
        : "「鍵」を配置して、鍵扉とペアリングさせてください";
    }
    if (linkingState.mode === "BUTTON_DOOR") {
      return linkingState.pendingType === "BUTTON_DOOR"
        ? "「ボタン扉」を配置して、ボタンとペアリングさせてください"
        : "「ボタン」を配置して、ボタン扉とペアリングさせてください";
    }
    return "ペアとなるギミックを配置してください";
  };

  return (
    <div className="min-h-screen bg-gray-950 text-white p-6">
      <div className="max-w-7xl mx-auto">
        {/* FormProviderで囲み、子コンポーネントがContext経由でReact Hook Formを扱えるようにする */}
        <FormProvider {...methods}>
          {/* onSubmitのデフォルト挙動を無効化 */}
          <form onSubmit={(e) => e.preventDefault()}>
            {/* ─── ヘッダー ─── */}
            <header className="select-none w-full mb-6">
              {/* 左側：基本情報フォーム（カード） */}
              <div className="min-w-0 w-full bg-slate-900 border border-slate-800 rounded-xl shadow-2xl p-4 flex flex-col justify-center">
                <EditorInfoHeader
                  isAdmin={isAdmin}
                  status={initialData?.status ?? "DRAFT"}
                  cols={cols}
                  rows={rows}
                  onConfigConfirm={() => pushHistory()}
                  onSizeChange={(r, c) => {
                    setRows(r);
                    setCols(c);
                    updateTilesSize(r, c);
                  }}
                  initialData={initialData}
                  user={user}
                  tiles={tiles}
                  entities={entities}
                  linkingState={linkingState}
                  canUndo={canUndo}
                  canRedo={canRedo}
                  onUndo={handleUndo}
                  onRedo={handleRedo}
                />
              </div>
            </header>

            {/* ─── メインレイアウト ─── */}
            <div className="flex flex-col md:flex-row gap-6 mt-6 items-start w-full">
              {/* 左サイドバー */}
              <aside className="w-64 flex-shrink-0 space-y-4">
                <TilePalette
                  selectedTile={selectedTile}
                  onSelect={(id) => {
                    if (linkingState.active && id !== " " && getEntityType(id) !== linkingState.pendingType) {
                      return toast.error("セット設置を優先するか、消しゴムでキャンセルしてください");
                    }
                    setSelectedTile(id);
                  }}
                  defaultOpen={initialPaletteOpen}
                />

                <DungeonMetadataCard
                  initialData={initialData}
                  isEditMode={isEditMode}
                  isAdmin={isAdmin}
                  defaultOpen={initialMetadataOpen}
                />
              </aside>

              {/* メインエリア：キャンバスコンテナ */}
              <div className="flex-1 flex flex-col min-w-0 relative h-[calc(100vh-220px)] min-h-[540px] w-full">
                {linkingState.active && (
                  <div className="absolute top-4 left-4 right-4 z-30 pointer-events-none animate-in fade-in slide-in-from-top-2 duration-200">
                    <div className="w-full bg-slate-900/95 backdrop-blur-md border-2 border-amber-500 rounded-xl px-5 py-3 flex items-center justify-between shadow-2xl shadow-black/80 pointer-events-auto">
                      <div className="flex items-center space-x-3">
                        <span className="relative flex h-3 w-3">
                          <span className="animate-ping absolute inline-flex h-full w-full rounded-full bg-amber-400 opacity-75"></span>
                          <span className="relative inline-flex rounded-full h-3 w-3 bg-amber-500"></span>
                        </span>
                        <p className="text-sm font-bold text-amber-400 tracking-wide">
                          {getLinkingGuideMessage()} （消しゴムでリセット）
                        </p>
                      </div>
                    </div>
                  </div>
                )}

                {/* メインエリア：キャンバス本体 */}
                <main className="bg-gray-900 border border-gray-800 rounded-xl overflow-auto p-12 h-full w-full flex">
                  <DungeonCanvasView
                    key={`${rows}-${cols}`}
                    tiles={tiles}
                    entities={entities}
                    rows={rows}
                    cols={cols}
                    images={images}
                    isLoaded={isLoaded}
                    linkingState={linkingState}
                    onCanvasAction={handleCanvasAction}
                  />
                </main>
              </div>
            </div>
          </form>
        </FormProvider>
      </div>
    </div>
  );
}
