import { TileConfig, TILE_CATEGORIES } from "@/game-core/types/tiles";

export const ENEMY_TILES = {
  E1: {
    name: "スライム",
    category: TILE_CATEGORIES.ENEMY,
    texture: "slime",
    enemyData: {
      id: "E_SLIME",
      name: "スライム",
      hp: 1,
      score: 500,
      xsize: 26,
      ysize: 22,
      xoffset: 3,
      yoffset: 8,
      speed: 30,
      moveType: "RANDOM",
      animType: "SINGLE",
      animSize: 8,
    },
  },
  E2: {
    name: "にこにこスライム",
    category: TILE_CATEGORIES.ENEMY,
    texture: "slimeBA2",
    enemyData: {
      id: "E_SLIME_2",
      name: "にこにこスライム",
      hp: 1,
      score: 700,
      xsize: 26,
      ysize: 22,
      xoffset: 3,
      yoffset: 8,
      speed: 60,
      moveType: "RANDOM",
      animType: "SINGLE",
      animSize: 12,
      frameRate: 10,
    },
  },
  E3: {
    name: "げきおこスライム",
    category: TILE_CATEGORIES.ENEMY,
    texture: "slimeBA3",
    enemyData: {
      id: "E_SLIME_3",
      name: "げきおこスライム",
      hp: 2,
      score: 1000,
      xsize: 26,
      ysize: 22,
      xoffset: 3,
      yoffset: 8,
      speed: 60,
      moveSteps: 1,
      moveType: "RANDOM",
      animType: "SINGLE",
      animSize: 12,
      frameRate: 18,
    },
  },
  EB1: {
    name: "ムテキてき",
    description: "とても強い。攻撃が効かない",
    category: TILE_CATEGORIES.ENEMY,
    texture: "blackMan",
    enemyData: {
      id: "E_BLACK_1",
      name: "ムテキてき",
      hp: 9999999,
      score: 9999999,
      xsize: 24,
      ysize: 24,
      xoffset: 4,
      yoffset: 4,
      speed: 60,
      moveSteps: 99,
      moveType: "HORIZONTAL",
      animType: "SINGLE",
      animSize: 12,
      frameRate: 12,
      isInvincible: true,
    },
  },
  EC1: {
    name: "ほのお",
    description: "追いかけてくる",
    category: TILE_CATEGORIES.ENEMY,
    texture: "flameRed1",
    enemyData: {
      id: "E_CHASE_1",
      name: "追いかけるてき",
      hp: 1,
      score: 500,
      xsize: 24,
      ysize: 24,
      xoffset: 4,
      yoffset: 4,
      speed: 30,
      moveSteps: 3,
      moveType: "CHASE",
      animType: "SINGLE",
      animSize: 4,
      frameRate: 12,
      isInvincible: false,
    },
  },
  EC2: {
    name: "あおいほのお",
    description: "追いかけてくる",
    category: TILE_CATEGORIES.ENEMY,
    texture: "flameBlue1",
    enemyData: {
      id: "E_CHASE_2",
      name: "追いかけるてき",
      hp: 1,
      score: 500,
      xsize: 24,
      ysize: 24,
      xoffset: 4,
      yoffset: 4,
      speed: 30,
      moveSteps: 3,
      moveType: "CHASE",
      animType: "SINGLE",
      animSize: 4,
      frameRate: 12,
      isInvincible: true,
    },
  },
} as const satisfies Record<string, TileConfig>;
