import { TileConfig, TILE_CATEGORIES } from "@/game-core/types/tiles";

export const ENEMY_TILES = {
  E1: {
    name: "スライム",
    category: TILE_CATEGORIES.ENEMY,
    texture: "slime",
    enemyData: {
      id: "E_SLIME",
      name: "スライム",
      hp: 1,
      score: 500,
      xsize: 26,
      ysize: 22,
      xoffset: 3,
      yoffset: 8,
      speed: 30,
      moveType: "RANDOM",
      animType: "SINGLE",
      animSize: 8,
    },
  },
  E2: {
    name: "にこにこスライム",
    category: TILE_CATEGORIES.ENEMY,
    texture: "slimeBA2",
    enemyData: {
      id: "E_SLIME_2",
      name: "にこにこスライム",
      hp: 1,
      score: 700,
      xsize: 26,
      ysize: 22,
      xoffset: 3,
      yoffset: 8,
      speed: 60,
      moveType: "RANDOM",
      animType: "SINGLE",
      animSize: 12,
      frameRate: 10,
    },
  },
  E3: {
    name: "げきおこスライム",
    category: TILE_CATEGORIES.ENEMY,
    texture: "slimeBA3",
    enemyData: {
      id: "E_SLIME_3",
      name: "げきおこスライム",
      hp: 2,
      score: 1000,
      xsize: 26,
      ysize: 22,
      xoffset: 3,
      yoffset: 8,
      speed: 60,
      moveSteps: 1,
      moveType: "RANDOM",
      animType: "SINGLE",
      animSize: 12,
      frameRate: 24,
    },
  },
  EB1: {
    name: "ムテキくろ",
    description: "とても強い。攻撃が効かない",
    category: TILE_CATEGORIES.ENEMY,
    texture: "blackMan",
    enemyData: {
      id: "E_BLACK_1",
      name: "ムテキくろ",
      hp: 9999999,
      score: 9999999,
      xsize: 24,
      ysize: 24,
      xoffset: 4,
      yoffset: 4,
      speed: 60,
      moveSteps: 99,
      moveType: "HORIZONTAL",
      animType: "SINGLE",
      animSize: 12,
      frameRate: 12,
      isInvincible: true,
    },
  },
  ER1: {
    name: "ムテキあか",
    description: "とても強い。攻撃が効かない",
    category: TILE_CATEGORIES.ENEMY,
    texture: "redEyeDice",
    enemyData: {
      id: "E_RED_1",
      name: "ムテキあか",
      hp: 9999999,
      score: 9999999,
      xsize: 24,
      ysize: 24,
      xoffset: 4,
      yoffset: 4,
      speed: 60,
      moveSteps: 99,
      moveType: "VERTICAL",
      animType: "SINGLE",
      animSize: 14,
      frameRate: 12,
      isInvincible: true,
    },
  },
  EC1: {
    name: "ほのお",
    description: "じわじわと追いかけてくる",
    category: TILE_CATEGORIES.ENEMY,
    texture: "flameRed1",
    enemyData: {
      id: "E_CHASE_1",
      name: "ほのお",
      hp: 1,
      score: 500,
      xsize: 24,
      ysize: 24,
      xoffset: 4,
      yoffset: 4,
      speed: 10,
      moveSteps: 3,
      moveType: "CHASE",
      animType: "SINGLE",
      animSize: 4,
      frameRate: 12,
      isInvincible: false,
    },
  },
  EC2: {
    name: "ムテキほのお",
    description: "じわじわと追いかけてくる。むてき",
    category: TILE_CATEGORIES.ENEMY,
    texture: "flameBlue1",
    enemyData: {
      id: "E_CHASE_2",
      name: "ムテキほのお",
      hp: 1,
      score: 500,
      xsize: 24,
      ysize: 24,
      xoffset: 4,
      yoffset: 4,
      speed: 20,
      moveSteps: 3,
      moveType: "CHASE",
      animType: "SINGLE",
      animSize: 4,
      frameRate: 12,
      isInvincible: true,
    },
  },
  ED1: {
    name: "ドッペル",
    description: "追いかけてくる。むてき",
    category: TILE_CATEGORIES.ENEMY,
    texture: "doppel1",
    enemyData: {
      id: "E_CHASE_3",
      name: "追いかけるてき",
      hp: 1,
      score: 500,
      xsize: 24,
      ysize: 24,
      xoffset: 4,
      yoffset: 4,
      speed: 60,
      moveSteps: 3,
      moveType: "CHASE",
      animType: "DIRECTIONAL",
      animSize: 12,
      frameRate: 12,
      isInvincible: false,
    },
  },
  EG1: {
    name: "ゴースト",
    description: "すり抜けてくる",
    category: TILE_CATEGORIES.ENEMY,
    texture: "ghost1",
    enemyData: {
      id: "E_GHOST_1",
      name: "ゴースト",
      hp: 1,
      score: 500,
      xsize: 24,
      ysize: 24,
      xoffset: 4,
      yoffset: 4,
      speed: 60,
      moveSteps: 6,
      moveType: "RANDOM",
      animType: "DIRECTIONAL_2",
      animSize: 12,
      frameRate: 6,
      isInvincible: false,
      isGhost: true,
    },
  },
  EKO: {
    name: "こおに",
    description: "みつけたら追いかけてくる",
    category: TILE_CATEGORIES.ENEMY,
    texture: "kooni",
    enemyData: {
      id: "E_KOONI",
      name: "こおに",
      hp: 1,
      score: 500,
      xsize: 24,
      ysize: 24,
      xoffset: 4,
      yoffset: 4,
      speed: 60,
      moveSteps: 3,
      moveType: "CHASE_2",
      animType: "DIRECTIONAL",
      animSize: 12,
      frameRate: 6,
      isInvincible: false,
      isGhost: false,
      chaseDistance: 5,
      speedUp: 1,
    },
  },
} as const satisfies Record<string, TileConfig>;
