import { TileConfig, TILE_CATEGORIES } from "@/game-core/types/tiles";

export const ENEMY_TILES = {
  E1: {
    name: "--未使用 スライム",
    category: TILE_CATEGORIES.ENEMY,
    texture: "slime",
    enemyData: {
      id: "E_SLIME",
      name: "スライム",
      hp: 1,
      score: 500,
      xsize: 26,
      ysize: 22,
      xoffset: 3,
      yoffset: 8,
      moveSteps: 1,
      speed: 30,
      moveType: "RANDOM",
      animType: "SINGLE",
      animSize: 8,
      isStealth: true,
    },
  },
  E2: {
    name: "にこにこスライム",
    category: TILE_CATEGORIES.ENEMY,
    texture: "slimeBA2",
    enemyData: {
      id: "E_SLIME_2",
      name: "にこにこスライム",
      hp: 1,
      score: 700,
      xsize: 26,
      ysize: 22,
      xoffset: 3,
      yoffset: 8,
      moveSteps: 1,
      speed: 60,
      moveType: "RANDOM",
      animType: "SINGLE",
      animSize: 12,
      frameRate: 10,
    },
  },
  E3: {
    name: "げきおこスライム",
    category: TILE_CATEGORIES.ENEMY,
    texture: "slimeBA3",
    enemyData: {
      id: "E_SLIME_3",
      name: "げきおこスライム",
      hp: 2,
      score: 1000,
      xsize: 26,
      ysize: 22,
      xoffset: 3,
      yoffset: 8,
      speed: 60,
      moveSteps: 1,
      moveType: "RANDOM",
      animType: "SINGLE",
      animSize: 12,
      frameRate: 32,
    },
  },
  EB1: {
    name: "ムテキくろ",
    description: "とても強い。攻撃が効かない",
    category: TILE_CATEGORIES.ENEMY,
    texture: "blackMan",
    enemyData: {
      id: "E_BLACK_1",
      name: "ムテキくろ",
      hp: 9999999,
      score: 9999999,
      xsize: 24,
      ysize: 24,
      xoffset: 4,
      yoffset: 4,
      speed: 60,
      moveSteps: 99,
      moveType: "HORIZONTAL",
      animType: "SINGLE",
      animSize: 12,
      frameRate: 12,
      isInvincible: true,
    },
  },
  ER1: {
    name: "ムテキあか",
    description: "とても強い。攻撃が効かない",
    category: TILE_CATEGORIES.ENEMY,
    texture: "redEyeDice",
    enemyData: {
      id: "E_RED_1",
      name: "ムテキあか",
      hp: 9999999,
      score: 9999999,
      xsize: 24,
      ysize: 24,
      xoffset: 4,
      yoffset: 4,
      speed: 60,
      moveSteps: 99,
      moveType: "VERTICAL",
      animType: "SINGLE",
      animSize: 14,
      frameRate: 12,
      isInvincible: true,
    },
  },
  EC1: {
    name: "ほのお",
    description: "じわじわと追いかけてくる",
    category: TILE_CATEGORIES.ENEMY,
    texture: "flameRed1",
    enemyData: {
      id: "E_CHASE_1",
      name: "ほのお",
      hp: 1,
      score: 600,
      xsize: 24,
      ysize: 24,
      xoffset: 4,
      yoffset: 4,
      speed: 10,
      moveSteps: 3,
      moveType: "CHASE",
      animType: "SINGLE",
      animSize: 4,
      frameRate: 12,
      isInvincible: false,
    },
  },
  EC2: {
    name: "ムテキほのお",
    description: "じわじわと追いかけてくる。むてき",
    category: TILE_CATEGORIES.ENEMY,
    texture: "flameBlue1",
    enemyData: {
      id: "E_CHASE_2",
      name: "ムテキほのお",
      hp: 9999999,
      score: 9999999,
      xsize: 24,
      ysize: 24,
      xoffset: 4,
      yoffset: 4,
      speed: 20,
      moveSteps: 3,
      moveType: "CHASE",
      animType: "SINGLE",
      animSize: 4,
      frameRate: 12,
      isInvincible: true,
    },
  },
  EDO: {
    name: "ドッペル",
    description: "動きをまねしてくる。",
    category: TILE_CATEGORIES.ENEMY,
    texture: "doppel1",
    enemyData: {
      id: "E_CHASE_3",
      name: "ドッペル",
      hp: 1,
      score: 800,
      xsize: 24,
      ysize: 24,
      xoffset: 4,
      yoffset: 4,
      speed: 60,
      moveSteps: 3,
      moveType: "MIRROR",
      animType: "DIRECTIONAL",
      animSize: 12,
      frameRate: 12,
      isInvincible: false,
    },
  },
  EG1: {
    name: "ゴースト",
    description: "すり抜けてくる",
    category: TILE_CATEGORIES.ENEMY,
    texture: "ghost1",
    enemyData: {
      id: "E_GHOST_1",
      name: "ゴースト",
      hp: 1,
      score: 800,
      xsize: 24,
      ysize: 24,
      xoffset: 4,
      yoffset: 4,
      speed: 60,
      moveSteps: 6,
      moveType: "RANDOM",
      animType: "DIRECTIONAL_2",
      animSize: 12,
      frameRate: 6,
      isInvincible: false,
      isGhost: true,
      isStealth: true,
      detectDistance: 8,
    },
  },
  EO1: {
    name: "あかおに",
    description: "みつけたら追いかけてくる",
    category: TILE_CATEGORIES.ENEMY,
    texture: "akaoni",
    enemyData: {
      id: "E_ONI1",
      name: "あかおに",
      hp: 1,
      score: 800,
      xsize: 24,
      ysize: 24,
      xoffset: 4,
      yoffset: 4,
      speed: 60,
      moveSteps: 3,
      moveType: "CHASE_2",
      animType: "DIRECTIONAL",
      animSize: 12,
      frameRate: 6,
      isInvincible: false,
      isGhost: false,
      chaseDistance: 5,
      speedUp: 1.1,
    },
  },
  EO2: {
    name: "あおおに",
    description: "みつけたら追いかけてくる。速い",
    category: TILE_CATEGORIES.ENEMY,
    texture: "aooni",
    enemyData: {
      id: "E_ONI2",
      name: "あおおに",
      hp: 1,
      score: 1000,
      xsize: 24,
      ysize: 24,
      xoffset: 4,
      yoffset: 4,
      speed: 60,
      moveSteps: 3,
      moveType: "CHASE_2",
      animType: "DIRECTIONAL",
      animSize: 12,
      frameRate: 6,
      isInvincible: false,
      isGhost: false,
      chaseDistance: 5,
      speedUp: 3.0,
    },
  },
  EDR: {
    name: "ドラゴン",
    description: "火を噴いてくる",
    category: TILE_CATEGORIES.ENEMY,
    texture: "dragon",
    enemyData: {
      id: "E_DRAGON",
      name: "ドラゴン",
      hp: 1,
      score: 1000,
      xsize: 24,
      ysize: 24,
      xoffset: 4,
      yoffset: 4,
      speed: 60,
      moveSteps: 3,
      moveType: "RANGED",
      rangedData: {
        bulletAnim: { key: "fireBall", animSize: 4, frameRate: 30, bodyRadius: 10, offsetX: 0, offsetY: 6 },
        bulletSpeed: 120,
        prepareTime: 1000,
        cooldown: 1000,
        shotCount: 1,
        // shotInterval: 300,
      },
      animType: "DIRECTIONAL",
      animSize: 12,
      frameRate: 6,
      isInvincible: false,
      isGhost: false,
      chaseDistance: 5,
      speedUp: 1.1,
    },
  },
  EDRR: {
    name: "レッドドラゴン",
    description: "めっちゃ火を噴いてくる",
    category: TILE_CATEGORIES.ENEMY,
    texture: "dragonRed",
    enemyData: {
      id: "E_DRAGON_RED",
      name: "レッドドラゴン",
      hp: 1,
      score: 1500,
      xsize: 24,
      ysize: 24,
      xoffset: 4,
      yoffset: 4,
      speed: 60,
      moveSteps: 3,
      moveType: "RANGED",
      rangedData: {
        bulletAnim: { key: "fireBall", animSize: 4, frameRate: 30, bodyRadius: 10, offsetX: 0, offsetY: 6 },
        bulletSpeed: 200,
        prepareTime: 1000,
        cooldown: 1000,
        shotCount: 3,
        shotInterval: 300,
      },
      animType: "DIRECTIONAL",
      animSize: 12,
      frameRate: 6,
      isInvincible: false,
      isGhost: false,
      chaseDistance: 5,
      speedUp: 1.1,
    },
  },
  ES: {
    name: "かげ",
    category: TILE_CATEGORIES.ENEMY,
    texture: "shadow",
    enemyData: {
      id: "E_SHADOW",
      name: "かげ",
      hp: 1,
      score: 800,
      xsize: 26,
      ysize: 22,
      xoffset: 3,
      yoffset: 8,
      speed: 80,
      moveSteps: 1,
      moveType: "RANDOM",
      animType: "SINGLE",
      animSize: 9,
      isStealth: true,
      detectDistance: 3,
    },
  },
  EM: {
    name: "マンチカン",
    category: TILE_CATEGORIES.ENEMY,
    texture: "munchkin",
    enemyData: {
      id: "E_MUNCHKIN",
      name: "マンチカン",
      hp: 1,
      score: 100,
      xsize: 26,
      ysize: 22,
      xoffset: 3,
      yoffset: 8,
      speed: 30,
      moveSteps: 1,
      moveType: "RANDOM",
      animType: "DIRECTIONAL",
      animSize: 12,
      frameRate: 6,
      isInvincible: true,
      isObstacle: true,
    },
  },
  EG: {
    name: "ゴーレム",
    category: TILE_CATEGORIES.ENEMY,
    texture: "golem",
    enemyData: {
      id: "E_GOLEM",
      name: "ゴーレム",
      hp: 3,
      score: 1500,
      xsize: 26,
      ysize: 22,
      xoffset: 3,
      yoffset: 8,
      speed: 30,
      moveSteps: 1,
      moveType: "CHASE_2",
      chaseDistance: 1.5,
      speedUp: 1,
      animType: "DIRECTIONAL",
      animSize: 12,
      frameRate: 6,
      stunDuration: 300,
    },
  },
  ECC: {
    name: "たいほう",
    category: TILE_CATEGORIES.ENEMY,
    texture: "cannon",
    enemyData: {
      id: "E_CANNON",
      name: "たいほう",
      hp: 1,
      score: 1500,
      xsize: 24,
      ysize: 24,
      xoffset: 4,
      yoffset: 4,
      speed: 0,
      moveSteps: 0,
      moveType: "RANGED",
      rangedData: {
        bulletAnim: { key: "cannonBall", animSize: 1, bodyRadius: 10, offsetX: 0, offsetY: 6 },
        bulletSpeed: 300,
        prepareTime: 1000,
        cooldown: 3000,
        shotCount: 1,
        shotInterval: 300,
      },
      animType: "DIRECTIONAL_3",
      animSize: 4,
      frameRate: 6,
      isInvincible: false,
      isGhost: false,
      chaseDistance: 10,
    },
  },
  // 画像の読み込み用宣言
  EFB: {
    name: "ファイアーボール",
    description: "ドラゴンの炎",
    category: TILE_CATEGORIES.ENEMY,
    texture: "fireBall",
  },
  ECCB: {
    name: "大砲の玉",
    category: TILE_CATEGORIES.ENEMY,
    texture: "cannonBall",
  },
} as const satisfies Record<string, TileConfig>;
