import { TileConfig, TILE_CATEGORIES } from "@/game-core/types/tiles";

export const GIMMICK_TILES = {
  ST: {
    name: "石",
    category: TILE_CATEGORIES.STONE,
    texture: "stone",
    stoneData: { id: "S_NORMAL", stoneType: "NORMAL", element: "STONE" },
  },
  STI: {
    name: "氷",
    category: TILE_CATEGORIES.STONE,
    texture: "iceStone",
    stoneData: { id: "S_ICE", stoneType: "NORMAL", element: "ICE" },
  },
  STB: {
    name: "壊れる石",
    category: TILE_CATEGORIES.STONE,
    texture: "stoneBreakable",
    stoneData: { id: "S_BREAKABLE", stoneType: "BREAKABLE", element: "STONE" },
  },
  STIB: {
    name: "壊れる氷",
    category: TILE_CATEGORIES.STONE,
    texture: "iceStoneBreakable",
    stoneData: { id: "S_BREAKABLE_ICE", stoneType: "BREAKABLE", element: "ICE" },
  },
  STH: {
    name: "重い石",
    category: TILE_CATEGORIES.STONE,
    texture: "heavyStone",
    stoneData: { id: "S_HEAVY", stoneType: "HEAVY", element: "STONE" },
  },
  STS: {
    name: "とげとげ石",
    category: TILE_CATEGORIES.STONE,
    texture: "spikyStone",
    stoneData: { id: "S_SPIKY", stoneType: "SPIKE", element: "STONE" },
  },
  BLR: {
    name: "右ブロック",
    category: TILE_CATEGORIES.STONE,
    texture: "blockRight",
    allowedDirection: "RIGHT",
    stoneData: { id: "B_RIGHT", stoneType: "NORMAL", element: "BLOCK" },
  },
  BLL: {
    name: "左ブロック",
    category: TILE_CATEGORIES.STONE,
    texture: "blockLeft",
    allowedDirection: "LEFT",
    stoneData: { id: "B_LEFT", stoneType: "NORMAL", element: "BLOCK" },
  },
  BLU: {
    name: "上ブロック",
    category: TILE_CATEGORIES.STONE,
    texture: "blockUp",
    allowedDirection: "UP",
    stoneData: { id: "B_UP", stoneType: "NORMAL", element: "BLOCK" },
  },
  BLD: {
    name: "下ブロック",
    category: TILE_CATEGORIES.STONE,
    texture: "blockDown",
    stoneData: { id: "B_DOWN", stoneType: "NORMAL", element: "BLOCK" },
  },
  BLH: {
    name: "横ブロック",
    category: TILE_CATEGORIES.STONE,
    texture: "blockHorizontal",
    allowedDirection: "HORIZONTAL",
    stoneData: { id: "B_HORIZONTAL", stoneType: "NORMAL", element: "BLOCK" },
  },
  BLV: {
    name: "縦ブロック",
    category: TILE_CATEGORIES.STONE,
    texture: "blockVertical",
    allowedDirection: "VERTICAL",
    stoneData: { id: "B_VERTICAL", stoneType: "NORMAL", element: "STONE" },
  },
  CBLR: {
    name: "赤ブロック",
    category: TILE_CATEGORIES.STONE,
    texture: "colorBlockRed",
    color: "RED",
    stoneData: { id: "CB_RED", stoneType: "NORMAL", element: "BLOCK" },
  },
  CBLB: {
    name: "青ブロック",
    category: TILE_CATEGORIES.STONE,
    texture: "colorBlockBlue",
    color: "BLUE",
    stoneData: { id: "CB_BLUE", stoneType: "NORMAL", element: "BLOCK" },
  },
  CBLY: {
    name: "黄ブロック",
    category: TILE_CATEGORIES.STONE,
    texture: "colorBlockYellow",
    color: "YELLOW",
    stoneData: { id: "CB_YELLOW", stoneType: "NORMAL", element: "BLOCK" },
  },
  CBLG: {
    name: "緑ブロック",
    category: TILE_CATEGORIES.STONE,
    texture: "colorBlockGreen",
    color: "GREEN",
    stoneData: { id: "CB_YELLOW", stoneType: "NORMAL", element: "BLOCK" },
  },
  GB: {
    name: "ボタン",
    category: TILE_CATEGORIES.GIMMICK,
    texture: "buttonTrigger",
    openFrame: 1,
    linkConfig: { entityType: "BUTTON", linkGroup: "BUTTON_DOOR", targetEntityType: "BUTTON_DOOR" },
  },
  GBD: {
    name: "扉",
    category: TILE_CATEGORIES.GIMMICK,
    texture: "buttonDoor",
    openFrame: 1,
    linkConfig: { entityType: "BUTTON_DOOR", linkGroup: "BUTTON_DOOR", targetEntityType: "BUTTON" },
  },
  GK: {
    name: "鍵",
    category: TILE_CATEGORIES.GIMMICK,
    texture: "keySilver",
    item: { id: "KEY_SILVER", name: "銀の鍵", type: "KEY", consumesOnUse: true },
    linkConfig: { entityType: "KEY", linkGroup: "KEY_DOOR", targetEntityType: "KEY_DOOR" },
  },
  GKD: {
    name: "扉",
    category: TILE_CATEGORIES.GIMMICK,
    texture: "keySilverDoor",
    openFrame: 1,
    isLocked: true,
    linkConfig: { entityType: "KEY_DOOR", linkGroup: "KEY_DOOR", targetEntityType: "KEY" },
  },
  GLS: {
    name: "レバースイッチ",
    category: TILE_CATEGORIES.GIMMICK,
    texture: "leverSwitch",
    openFrame: 1,
    linkConfig: { entityType: "LEVER_SWITCH", linkGroup: "LEVER_SWITCH_DOOR", targetEntityType: "LEVER_SWITCH_DOOR" },
  },
  GLSD: {
    name: "扉",
    category: TILE_CATEGORIES.GIMMICK,
    texture: "leverSwitchDoor",
    openFrame: 1,
    linkConfig: { entityType: "LEVER_SWITCH_DOOR", linkGroup: "LEVER_SWITCH_DOOR", targetEntityType: "LEVER_SWITCH" },
  },
  GDDL: {
    name: "左扉",
    category: TILE_CATEGORIES.GIMMICK,
    texture: "doorDirectionLeft",
    openFrame: 1,
    allowedDirection: "LEFT",
  },
  GWI: {
    name: "ワープ入口",
    category: TILE_CATEGORIES.GIMMICK,
    texture: "warpIn",
    linkConfig: { entityType: "WARP_IN", linkGroup: "WARP", targetEntityType: "WARP_OUT" },
  },
  GWO: {
    name: "ワープ出口",
    category: TILE_CATEGORIES.GIMMICK,
    texture: "warpOut",
    linkConfig: { entityType: "WARP_OUT", linkGroup: "WARP", targetEntityType: "WARP_IN" },
  },
  GWT1: {
    name: "ワープ1",
    category: TILE_CATEGORIES.GIMMICK,
    texture: "warpTwoWay1",
    linkConfig: { entityType: "WARP_TWO_WAY1", linkGroup: "WARP_TWO_WAY", targetEntityType: "WARP_TWO_WAY2" },
  },
  GWT2: {
    name: "ワープ2",
    category: TILE_CATEGORIES.GIMMICK,
    texture: "warpTwoWay2",
    linkConfig: { entityType: "WARP_TWO_WAY2", linkGroup: "WARP_TWO_WAY", targetEntityType: "WARP_TWO_WAY1" },
  },
} as const satisfies Record<string, TileConfig>;
