import { TileConfig, TILE_CATEGORIES } from "@/game-core/types/tiles";

export const GIMMICK_TILES = {
  R1: {
    name: "石",
    category: TILE_CATEGORIES.STONE,
    texture: "stone",
    stoneData: { id: "S_NORMAL", stoneType: "NORMAL", element: "STONE" },
  },
  R3: {
    name: "氷",
    category: TILE_CATEGORIES.STONE,
    texture: "iceStone",
    stoneData: { id: "S_ICE", stoneType: "NORMAL", element: "ICE" },
  },
  R5: {
    name: "壊れる石",
    category: TILE_CATEGORIES.STONE,
    texture: "stoneBreakable",
    stoneData: { id: "S_BREAKABLE", stoneType: "BREAKABLE", element: "STONE" },
  },
  R6: {
    name: "壊れる氷",
    category: TILE_CATEGORIES.STONE,
    texture: "iceStoneBreakable",
    stoneData: { id: "S_BREAKABLE_ICE", stoneType: "BREAKABLE", element: "ICE" },
  },
  R7: {
    name: "重い石",
    category: TILE_CATEGORIES.STONE,
    texture: "heavyStone",
    stoneData: { id: "S_HEAVY", stoneType: "HEAVY", element: "STONE" },
  },
  R8: {
    name: "とげとげ石",
    category: TILE_CATEGORIES.STONE,
    texture: "spikyStone",
    stoneData: { id: "S_SPIKY", stoneType: "SPIKE", element: "STONE" },
  },
  BR: {
    name: "ブロック右",
    category: TILE_CATEGORIES.STONE,
    texture: "blockRight",
    stoneData: { id: "B_RIGHT", stoneType: "NORMAL", element: "STONE", allowedDirection: "RIGHT" },
  },
  BL: {
    name: "ブロック左",
    category: TILE_CATEGORIES.STONE,
    texture: "blockLeft",
    stoneData: { id: "B_LEFT", stoneType: "NORMAL", element: "STONE", allowedDirection: "LEFT" },
  },
  BU: {
    name: "ブロック上",
    category: TILE_CATEGORIES.STONE,
    texture: "blockUp",
    stoneData: { id: "B_UP", stoneType: "NORMAL", element: "STONE", allowedDirection: "UP" },
  },
  BD: {
    name: "ブロック下",
    category: TILE_CATEGORIES.STONE,
    texture: "blockDown",
    stoneData: { id: "B_DOWN", stoneType: "NORMAL", element: "STONE", allowedDirection: "DOWN" },
  },
  BH: {
    name: "ブロック左右",
    category: TILE_CATEGORIES.STONE,
    texture: "blockHorizontal",
    stoneData: { id: "B_HORIZONTAL", stoneType: "NORMAL", element: "STONE", allowedDirection: "HORIZONTAL" },
  },
  BV: {
    name: "ブロック上下",
    category: TILE_CATEGORIES.STONE,
    texture: "blockVertical",
    stoneData: { id: "B_VERTICAL", stoneType: "NORMAL", element: "STONE", allowedDirection: "VERTICAL" },
  },
  B1: {
    name: "ボタン",
    category: TILE_CATEGORIES.GIMMICK,
    texture: "buttonTrigger",
    openFrame: 1,
    linkConfig: { entityType: "BUTTON", linkGroup: "BUTTON_DOOR", targetEntityType: "BUTTON_DOOR" },
  },
  D1: {
    name: "ボタン扉",
    category: TILE_CATEGORIES.GIMMICK,
    texture: "buttonDoor",
    openFrame: 1,
    linkConfig: { entityType: "BUTTON_DOOR", linkGroup: "BUTTON_DOOR", targetEntityType: "BUTTON" },
  },
  K1: {
    name: "鍵",
    category: TILE_CATEGORIES.GIMMICK,
    texture: "keySilver",
    item: { id: "KEY_SILVER", name: "銀の鍵", type: "KEY", consumesOnUse: true },
    linkConfig: { entityType: "KEY", linkGroup: "KEY_DOOR", targetEntityType: "KEY_DOOR" },
  },
  KD1: {
    name: "鍵扉",
    category: TILE_CATEGORIES.GIMMICK,
    texture: "keySilverDoor",
    openFrame: 1,
    isLocked: true,
    linkConfig: { entityType: "KEY_DOOR", linkGroup: "KEY_DOOR", targetEntityType: "KEY" },
  },
  WI1: {
    name: "ワープ入口",
    category: TILE_CATEGORIES.GIMMICK,
    texture: "warpIn",
    linkConfig: { entityType: "WARP_IN", linkGroup: "WARP", targetEntityType: "WARP_OUT" },
  },
  WO1: {
    name: "ワープ出口",
    category: TILE_CATEGORIES.GIMMICK,
    texture: "warpOut",
    linkConfig: { entityType: "WARP_OUT", linkGroup: "WARP", targetEntityType: "WARP_IN" },
  },
  WT1: {
    name: "ワープ1",
    category: TILE_CATEGORIES.GIMMICK,
    texture: "warpTwoWay1",
    linkConfig: { entityType: "WARP_TWO_WAY1", linkGroup: "WARP_TWO_WAY", targetEntityType: "WARP_TWO_WAY2" },
  },
  WT2: {
    name: "ワープ2",
    category: TILE_CATEGORIES.GIMMICK,
    texture: "warpTwoWay2",
    linkConfig: { entityType: "WARP_TWO_WAY2", linkGroup: "WARP_TWO_WAY", targetEntityType: "WARP_TWO_WAY1" },
  },
} as const satisfies Record<string, TileConfig>;
